controller_list:
  - name: fake_manipulator_controller
    type: $(arg fake_execution_type)
    joints:
      - robot_joint_1
      - robot_joint_2
      - robot_joint_3
      - robot_joint_4
      - robot_joint_5
      - robot_joint_6
initial:  # Define initial robot poses per group
#  - group: manipulator
#    pose: home

  []