# System Settings
# -------------------------------
# Setting/Parameter file for the general system

general:
  # Needs to match the arguments set in the main launch file
  simulation:       true
  robot_count:      1
  global_ref_frame: "world"
  robot_frame:      "robot_base_link"
  # tool_frame:       "robot_tcp"   
  tool_frame:       "robot_eef_tcp"

  # manipulator:      "robot_manipulator"
  manipulator:      "robot_end_effector"
  robot_type:       "irb6660"

  robot_prefix:     # Used for Joint-State-Publisher Node
    robot_1:  "robot"