GP_manipulator:
  kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
  kinematics_solver_timeout: 0.005
  solve_type: Speed
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_attempts: 10

ABB_manipulator:
  kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
  kinematics_solver_timeout: 0.005
  solve_type: Speed
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_attempts: 10