# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: gp400_manipulator
  joint_model_group_pose: gp400_home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - gp400_joint_1
    - gp400_joint_2
    - gp400_joint_3
    - gp400_joint_4
    - gp400_joint_5
    - gp400_joint_6
    - irb6660_joint_1
    - irb6660_joint_2
    - irb6660_joint_3
    - irb6660_joint_4
    - irb6660_joint_5
    - irb6660_joint_6
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: gp400_manipulator_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - gp400_joint_1
      - gp400_joint_2
      - gp400_joint_3
      - gp400_joint_4
      - gp400_joint_5
      - gp400_joint_6
  - name: irb6660_manipulator_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - irb6660_joint_1
      - irb6660_joint_2
      - irb6660_joint_3
      - irb6660_joint_4
      - irb6660_joint_5
      - irb6660_joint_6